apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport-svc
  namespace: 3tier
  labels:
    app: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3308
      targetPort: 3306
      nodePort: 30005
