apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  namespace: 3tier
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 82
      targetPort: 80
      nodePort: 30003
