apiVersion: v1
kind: Service
metadata:
  name: python-nodeportsvc
  namespace: 3tier
  labels:
    app: python
spec:
  type: NodePort
  selector:
    app: python
  ports:
    - port: 5002
      targetPort: 5000
      nodePort: 30004
