apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-svc
  namespace: 3tier
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 83
      targetPort: 80
