apiVersion: v1
kind: Service
metadata:
  name: python-loadbalancer-svc
  namespace: 3tier
  labels:
    app: python
spec:
  type: LoadBalancer
  selector:
    app: python
  ports:
    - port: 5003
      targetPort: 5000
